"""add native_language to profiles and checkin fields to assessment_sessions

Revision ID: 9d77dfce01ee
Revises: 99f8455a6a47
Create Date: 2026-07-14 23:54:00.329879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d77dfce01ee'
down_revision = '99f8455a6a47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stress_level', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('hours_slept', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('caffeine_today', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('medication', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('current_mood', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('wearing_glasses', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('distractions', sa.String(length=20), nullable=True))
        # Not auto-detected by Alembic's autogenerate (a known limitation
        # for new CheckConstraints) — added manually to match
        # models/assessment.py's ck_assessment_sessions_hours_slept_range.
        batch_op.create_check_constraint(
            'ck_assessment_sessions_hours_slept_range',
            'hours_slept IS NULL OR (hours_slept >= 0 AND hours_slept <= 24)',
        )

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('native_language', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_column('native_language')

    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_constraint('ck_assessment_sessions_hours_slept_range', type_='check')
        batch_op.drop_column('distractions')
        batch_op.drop_column('wearing_glasses')
        batch_op.drop_column('current_mood')
        batch_op.drop_column('medication')
        batch_op.drop_column('caffeine_today')
        batch_op.drop_column('hours_slept')
        batch_op.drop_column('stress_level')

    # ### end Alembic commands ###
