"""add unique constraint on assessment_results assessment_id domain

Revision ID: ba233e13e734
Revises: 20f324be9f40
Create Date: 2026-07-14 11:34:47.608002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba233e13e734'
down_revision = '20f324be9f40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_assessment_results_assessment_id_domain', ['assessment_id', 'domain'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_constraint('uq_assessment_results_assessment_id_domain', type_='unique')

    # ### end Alembic commands ###
