"""add guest tables and research metadata/version columns

Revision ID: c6a063bf8aa7
Revises: 9d77dfce01ee
Create Date: 2026-07-20 07:45:47.280839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6a063bf8aa7'
down_revision = '9d77dfce01ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guest_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_uuid', sa.String(length=36), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.String(length=30), nullable=True),
    sa.Column('education', sa.String(length=50), nullable=True),
    sa.Column('dominant_hand', sa.String(length=20), nullable=True),
    sa.Column('native_language', sa.String(length=60), nullable=True),
    sa.Column('claimed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('age IS NULL OR (age >= 1 AND age <= 120)', name='ck_guest_profiles_age_range'),
    sa.ForeignKeyConstraint(['claimed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_profiles_claimed_by_user_id'), ['claimed_by_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_guest_profiles_guest_uuid'), ['guest_uuid'], unique=True)

    op.create_table('guest_assessment_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_profile_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sleep_quality', sa.String(length=20), nullable=True),
    sa.Column('stress_level', sa.String(length=20), nullable=True),
    sa.Column('hours_slept', sa.Float(), nullable=True),
    sa.Column('caffeine_today', sa.String(length=20), nullable=True),
    sa.Column('medication', sa.String(length=200), nullable=True),
    sa.Column('current_mood', sa.String(length=20), nullable=True),
    sa.Column('wearing_glasses', sa.Boolean(), nullable=True),
    sa.Column('distractions', sa.String(length=20), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('assessment_version', sa.String(length=20), nullable=True),
    sa.Column('algorithm_version', sa.String(length=20), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'completed')", name='ck_guest_assessment_sessions_status'),
    sa.CheckConstraint('duration IS NULL OR duration >= 0', name='ck_guest_assessment_sessions_duration_nonneg'),
    sa.CheckConstraint('hours_slept IS NULL OR (hours_slept >= 0 AND hours_slept <= 24)', name='ck_guest_assessment_sessions_hours_slept_range'),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)', name='ck_guest_assessment_sessions_overall_score_range'),
    sa.ForeignKeyConstraint(['guest_profile_id'], ['guest_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('guest_assessment_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_assessment_sessions_guest_profile_id'), ['guest_profile_id'], unique=False)
        batch_op.create_index('ix_guest_assessment_sessions_guest_profile_id_status', ['guest_profile_id', 'status'], unique=False)

    op.create_table('guest_assessment_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('average_time', sa.Float(), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('raw_data', sa.JSON(), nullable=True),
    sa.Column('game_version', sa.String(length=20), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('accuracy IS NULL OR (accuracy >= 0 AND accuracy <= 100)', name='ck_guest_assessment_results_accuracy_range'),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_guest_assessment_results_score_range'),
    sa.ForeignKeyConstraint(['assessment_id'], ['guest_assessment_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('assessment_id', 'domain', name='uq_guest_assessment_results_assessment_id_domain')
    )
    with op.batch_alter_table('guest_assessment_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guest_assessment_results_assessment_id'), ['assessment_id'], unique=False)

    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('game_version', sa.String(length=20), nullable=True))

    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_metadata', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('assessment_version', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('algorithm_version', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_column('algorithm_version')
        batch_op.drop_column('assessment_version')
        batch_op.drop_column('session_metadata')

    with op.batch_alter_table('assessment_results', schema=None) as batch_op:
        batch_op.drop_column('game_version')

    with op.batch_alter_table('guest_assessment_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_assessment_results_assessment_id'))

    op.drop_table('guest_assessment_results')
    with op.batch_alter_table('guest_assessment_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_guest_assessment_sessions_guest_profile_id_status')
        batch_op.drop_index(batch_op.f('ix_guest_assessment_sessions_guest_profile_id'))

    op.drop_table('guest_assessment_sessions')
    with op.batch_alter_table('guest_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guest_profiles_guest_uuid'))
        batch_op.drop_index(batch_op.f('ix_guest_profiles_claimed_by_user_id'))

    op.drop_table('guest_profiles')
    # ### end Alembic commands ###
