"""add family_history to checkin fields

Revision ID: f415a080b250
Revises: c6a063bf8aa7
Create Date: 2026-07-20 19:05:56.246928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f415a080b250'
down_revision = 'c6a063bf8aa7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_history', sa.String(length=20), nullable=True))

    with op.batch_alter_table('guest_assessment_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('family_history', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('guest_assessment_sessions', schema=None) as batch_op:
        batch_op.drop_column('family_history')

    with op.batch_alter_table('assessment_sessions', schema=None) as batch_op:
        batch_op.drop_column('family_history')

    # ### end Alembic commands ###
